### ISSUE TITLE
InnovatED

### ISSUE THREAD

**Issue by sprinzz** [sprinzz/fbe_web#43]
Redevelop program website

**Comment by mua-murray** [comment]
Mim and Nicole to provide structure and content.
Proposed development phase 10-21 May.
[Website Objectives for InnovatED siteFINAL.docx](https://github.com/sprinzz/fbe_web/files/6395140/Website.Objectives.for.InnovatED.siteFINAL.docx)

**Comment by sprinzz** [comment]
Site setup and live
