### ISSUE TITLE
Landing page - Master of Management Suite

### ISSUE THREAD

**Issue by sprinzz** [sprinzz/fbe_web#6]
[https://study.unimelb.edu.au/lp/fbe/master-of-management-suite](https://study.unimelb.edu.au/lp/fbe/master-of-management-suite)
Create a landing page in /lp/fbe on Study for the MM suite of programs similar to [Fine Arts and Music](https://study.unimelb.edu.au/lp/grad/sy2021/fine-arts-and-music)

**Comment by mua-murray** [comment]
MM suite page created https://study.unimelb.edu.au/lp/fbe/master-of-management-suite
